import type { Locale } from "@/components/i18n/LocaleContext";

export const authCopy = {
  th: {
    brandTagline: "แพลตฟอร์มจัดการสต็อกร้านค้ารายย่อย",
    tabs: {
      login: "เข้าสู่ระบบ",
      register: "สมัครสมาชิก",
      forgot: "ลืมรหัสผ่าน",
    },
    login: {
      identifier: "อีเมล หรือชื่อผู้ใช้",
      identifierPlaceholder: "กรอกอีเมลหรือชื่อผู้ใช้",
      identifierHint: "เข้าสู่ระบบด้วย username ได้หากบัญชีตั้งรหัสผ่านไว้แล้ว",
      password: "รหัสผ่าน",
      passwordPlaceholder: "กรอกรหัสผ่าน",
      submit: "เข้าสู่ระบบ",
      submitting: "กำลังเข้าสู่ระบบ...",
      noAccount: "ยังไม่มีบัญชี?",
      register: "สมัครสมาชิก",
      forgot: "ลืมรหัสผ่าน?",
      resend: "ส่งลิงก์ยืนยันอีเมลอีกครั้ง",
      resending: "กำลังส่ง...",
      resent: "ส่งลิงก์ยืนยันใหม่ไปที่อีเมลของคุณแล้ว",
      otp: "กรอกรหัส 6 หลักจากแอป Authenticator ของคุณ",
      recovery: "กรอกรหัสกู้คืนที่ได้รับตอนเปิดใช้งาน 2 ขั้นตอน",
      otpLabel: "รหัสยืนยัน 2 ขั้นตอน",
      recoveryLabel: "รหัสกู้คืน",
      verify: "ยืนยัน",
      verifying: "กำลังยืนยัน...",
      useRecovery: "ใช้แอปยืนยันไม่ได้? ใช้รหัสกู้คืน",
      useOtp: "กลับไปกรอกรหัสจากแอป",
    },
    register: {
      firstName: "ชื่อ",
      lastName: "นามสกุล",
      email: "อีเมล",
      password: "รหัสผ่าน",
      confirmPassword: "ยืนยันรหัสผ่าน",
      firstNamePlaceholder: "กรอกชื่อ",
      lastNamePlaceholder: "กรอกนามสกุล",
      emailPlaceholder: "กรอกอีเมล",
      passwordPlaceholder: "กรอกรหัสผ่าน",
      confirmPlaceholder: "กรอกรหัสผ่านอีกครั้ง",
      emailHint: "ระบบจะสร้าง username จากส่วนหน้าอีเมลให้อัตโนมัติ",
      passwordHint: "อย่างน้อย 8 ตัวอักษร และต้องมีตัวพิมพ์เล็ก ตัวพิมพ์ใหญ่ ตัวเลข และสัญลักษณ์พิเศษ",
      submit: "สมัครสมาชิก",
      submitting: "กำลังสมัคร...",
      sentTitle: "ส่งลิงก์ยืนยันไปที่",
      sentBody: "แล้ว กรุณากดลิงก์ในอีเมลเพื่อเปิดใช้งานบัญชี จากนั้นจึงเข้าสู่ระบบได้ ลิงก์มีอายุ 24 ชั่วโมง",
      sentHint: "ไม่ได้รับอีเมล? ลองดูในกล่องจดหมายขยะ หรือขอลิงก์ใหม่ได้จากหน้าเข้าสู่ระบบ",
      sentFailedTitle: "สมัครสมาชิกสำเร็จแล้ว แต่ส่งอีเมลยืนยันไปที่",
      sentFailedBody: "ไม่สำเร็จ บัญชีของคุณถูกสร้างเรียบร้อยแล้ว ไม่ต้องสมัครใหม่",
      sentFailedHint: "กรุณากดขอลิงก์ยืนยันอีกครั้งจากหน้าเข้าสู่ระบบ หากยังไม่ได้รับ กรุณาติดต่อผู้ดูแลระบบ",
      goLogin: "ไปหน้าเข้าสู่ระบบ",
      haveAccount: "มีบัญชีแล้ว?",
      login: "เข้าสู่ระบบ",
    },
    forgot: {
      email: "อีเมลที่ลงทะเบียนไว้",
      emailPlaceholder: "กรอกอีเมล",
      hint: "การรีเซ็ตรหัสผ่านจะใช้ได้เฉพาะบัญชีที่มีอีเมลผูกไว้เท่านั้น",
      submit: "ส่งลิงก์รีเซ็ตรหัสผ่าน",
      submitting: "กำลังส่ง...",
      sent: "ถ้าอีเมลนี้มีอยู่ในระบบ เราได้ส่งลิงก์รีเซ็ตรหัสผ่านไปให้แล้ว กรุณาตรวจสอบกล่องจดหมาย รวมถึงจดหมายขยะ",
      back: "กลับไปเข้าสู่ระบบ",
    },
    reset: {
      title: "ตั้งรหัสผ่านใหม่",
      description: "กรอกรหัสผ่านใหม่ที่ต้องการใช้เข้าสู่ระบบครั้งต่อไป",
      password: "รหัสผ่านใหม่",
      confirm: "ยืนยันรหัสผ่านใหม่",
      placeholder: "กรอกรหัสผ่าน",
      hint: "อย่างน้อย 8 ตัวอักษร และต้องมีตัวพิมพ์เล็ก ตัวพิมพ์ใหญ่ ตัวเลข และสัญลักษณ์พิเศษ",
      submit: "ตั้งรหัสผ่านใหม่",
      submitting: "กำลังบันทึก...",
      invalid: "ลิงก์ไม่ถูกต้อง กรุณาขอลิงก์ตั้งรหัสผ่านใหม่อีกครั้ง",
      requestNew: "ขอลิงก์ใหม่",
    },
  },
  en: {
    brandTagline: "Back-office stock management for retail shops",
    tabs: { login: "Log in", register: "Sign up", forgot: "Forgot password" },
    login: {
      identifier: "Email or username",
      identifierPlaceholder: "Enter your email or username",
      identifierHint: "You can use your username if your account has a password.",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Log in",
      submitting: "Logging in...",
      noAccount: "Don't have an account?",
      register: "Sign up",
      forgot: "Forgot password?",
      resend: "Resend verification email",
      resending: "Sending...",
      resent: "A new verification link has been sent to your email.",
      otp: "Enter the 6-digit code from your authenticator app.",
      recovery: "Enter a recovery code from your two-step verification setup.",
      otpLabel: "Two-step verification code",
      recoveryLabel: "Recovery code",
      verify: "Verify",
      verifying: "Verifying...",
      useRecovery: "Can't use your app? Use a recovery code",
      useOtp: "Back to authenticator code",
    },
    register: {
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm password",
      firstNamePlaceholder: "Enter your first name",
      lastNamePlaceholder: "Enter your last name",
      emailPlaceholder: "Enter your email",
      passwordPlaceholder: "Enter your password",
      confirmPlaceholder: "Enter your password again",
      emailHint: "A username will be created automatically from your email.",
      passwordHint: "At least 8 characters with one lowercase, uppercase, number, and special character.",
      submit: "Sign up",
      submitting: "Signing up...",
      sentTitle: "A verification link was sent to",
      sentBody: ". Open the email to activate your account, then log in. The link expires in 24 hours.",
      sentHint: "Didn't receive it? Check your spam folder or request a new link from the login page.",
      sentFailedTitle: "Your account was created, but we could not send the verification email to",
      sentFailedBody: ". Your account already exists — there is no need to sign up again.",
      sentFailedHint: "Please request a new verification link from the login page. If it still does not arrive, contact an administrator.",
      goLogin: "Go to log in",
      haveAccount: "Already have an account?",
      login: "Log in",
    },
    forgot: {
      email: "Registered email",
      emailPlaceholder: "Enter your email",
      hint: "Password reset is available only for accounts with a linked email.",
      submit: "Send reset link",
      submitting: "Sending...",
      sent: "If this email exists in our system, we have sent a password reset link. Please check your inbox and spam folder.",
      back: "Back to log in",
    },
    reset: {
      title: "Reset password",
      description: "Enter a new password to use the next time you log in.",
      password: "New password",
      confirm: "Confirm new password",
      placeholder: "Enter your password",
      hint: "At least 8 characters with one lowercase, uppercase, number, and special character.",
      submit: "Reset password",
      submitting: "Saving...",
      invalid: "This link is invalid. Please request a new password reset link.",
      requestNew: "Request a new link",
    },
  },
} as const;

export function getAuthCopy(locale: Locale) {
  return authCopy[locale];
}
